#!/usr/bin/env bash
# build-cloud-manifest.sh — regenerate cloud-kit/MANIFEST (the files cloud-kit/install.sh
# downloads). Run after adding/removing a rule, hook, command, skill or output-style file.
#   bash scripts/build-cloud-manifest.sh          # rewrite
#   bash scripts/build-cloud-manifest.sh --check  # fail if stale
set -euo pipefail
cd "$(dirname "$0")/.."
new=$( { echo "# generated by scripts/build-cloud-manifest.sh — do not edit"; \
  find cloud-kit/rules cloud-kit/hooks commands skills output-styles -type f ! -name '.*' | LC_ALL=C sort; } )
paths=$(tail -n +2 <<< "$new")
if grep -q ' ' <<< "$paths"; then
  echo "FAIL: cloud-kit can't fetch paths with spaces:"; grep ' ' <<< "$paths"; exit 1
fi
if [ "${1:-}" = "--check" ]; then
  if [ "$new" != "$(cat cloud-kit/MANIFEST 2>/dev/null)" ]; then
    echo "FAIL: cloud-kit/MANIFEST is stale — run scripts/build-cloud-manifest.sh"; exit 1
  fi
  echo "OK: cloud-kit/MANIFEST up to date"
else
  printf '%s\n' "$new" > cloud-kit/MANIFEST
fi
